"""create cx domain tables

Revision ID: 28771d38c25c
Revises: 
Create Date: 2026-10-06 13:03:46.000385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28771d38c25c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slug = lower(slug) AND slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name='ck_brands_slug_format'),
    sa.CheckConstraint('char_length(btrim(name)) > 0', name='ck_brands_name_not_blank'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('customers',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("email = lower(email) AND position('@' in email) > 1", name='ck_customers_email_format'),
    sa.CheckConstraint('char_length(btrim(full_name)) > 0', name='ck_customers_name_not_blank'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name='fk_customers_brand_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'email', name='uq_customers_brand_email'),
    sa.UniqueConstraint('id', 'brand_id', name='uq_customers_id_brand')
    )
    op.create_table('knowledge_base_entries',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('return_policy', 'refund_policy', 'shipping_policy', 'cancellation_policy', name='knowledge_category', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(btrim(body)) > 0', name='ck_knowledge_body_not_blank'),
    sa.CheckConstraint('char_length(btrim(title)) > 0', name='ck_knowledge_title_not_blank'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name='fk_knowledge_brand_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'category', name='uq_knowledge_brand_category')
    )
    op.create_table('orders',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('order_number', sa.String(length=40), nullable=False),
    sa.Column('product_name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'shipped', 'delivered', 'cancelled', name='order_status', native_enum=False, length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(btrim(order_number)) > 0', name='ck_orders_order_number_not_blank'),
    sa.CheckConstraint('char_length(btrim(product_name)) > 0', name='ck_orders_product_name_not_blank'),
    sa.CheckConstraint('currency = upper(currency) AND char_length(currency) = 3', name='ck_orders_currency_code'),
    sa.CheckConstraint('total_cents >= 0', name='ck_orders_total_cents_nonnegative'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name='fk_orders_brand_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id', 'brand_id'], ['customers.id', 'customers.brand_id'], name='fk_orders_customer_brand', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'order_number', name='uq_orders_brand_order_number'),
    sa.UniqueConstraint('id', 'brand_id', name='uq_orders_id_brand'),
    sa.UniqueConstraint('id', 'customer_id', 'brand_id', name='uq_orders_id_customer_brand')
    )
    op.create_index('ix_orders_customer_id', 'orders', ['customer_id'], unique=False)
    op.create_table('conversations',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', name='conversation_status', native_enum=False, length=32), server_default='open', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(btrim(subject)) > 0', name='ck_conversations_subject_not_blank'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name='fk_conversations_brand_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id', 'brand_id'], ['customers.id', 'customers.brand_id'], name='fk_conversations_customer_brand', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id', 'customer_id', 'brand_id'], ['orders.id', 'orders.customer_id', 'orders.brand_id'], name='fk_conversations_order_customer_brand', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'brand_id', name='uq_conversations_id_brand')
    )
    op.create_index('ix_conversations_brand_status', 'conversations', ['brand_id', 'status'], unique=False)
    op.create_index('ix_conversations_customer_id', 'conversations', ['customer_id'], unique=False)
    op.create_index('ix_conversations_order_id', 'conversations', ['order_id'], unique=False)
    op.create_table('messages',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('author_type', sa.Enum('customer', 'agent', name='message_author', native_enum=False, length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(btrim(body)) > 0', name='ck_messages_body_not_blank'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name='fk_messages_brand_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conversation_id', 'brand_id'], ['conversations.id', 'conversations.brand_id'], name='fk_messages_conversation_brand', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'conversation_id', 'author_type', name='uq_messages_id_conversation_author')
    )
    op.create_index('ix_messages_brand_id', 'messages', ['brand_id'], unique=False)
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('ai_generation_logs',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('customer_message_id', sa.Uuid(), nullable=False),
    sa.Column('message_author_type', sa.String(length=32), server_default=sa.text("'customer'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("message_author_type = 'customer'", name='ck_ai_generation_logs_customer_message'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name='fk_ai_generation_logs_brand_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conversation_id', 'brand_id'], ['conversations.id', 'conversations.brand_id'], name='fk_ai_generation_logs_conversation_brand', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_message_id', 'conversation_id', 'message_author_type'], ['messages.id', 'messages.conversation_id', 'messages.author_type'], name='fk_ai_generation_logs_customer_message', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_generation_logs_brand_id', 'ai_generation_logs', ['brand_id'], unique=False)
    op.create_index('ix_ai_generation_logs_conversation_created', 'ai_generation_logs', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_ai_generation_logs_customer_message_id', 'ai_generation_logs', ['customer_message_id'], unique=False)
    _create_updated_at_triggers()
    # ### end Alembic commands ###


UPDATED_AT_TABLES = (
    "brands",
    "customers",
    "knowledge_base_entries",
    "orders",
    "conversations",
    "messages",
)


def _create_updated_at_triggers() -> None:
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            NEW.updated_at = CURRENT_TIMESTAMP;
            RETURN NEW;
        END;
        $$
        """
    )
    for table_name in UPDATED_AT_TABLES:
        op.execute(
            f"""
            CREATE TRIGGER trg_{table_name}_set_updated_at
            BEFORE UPDATE ON {table_name}
            FOR EACH ROW
            EXECUTE FUNCTION set_updated_at()
            """
        )


def _drop_updated_at_triggers() -> None:
    for table_name in UPDATED_AT_TABLES:
        op.execute(
            f"DROP TRIGGER IF EXISTS trg_{table_name}_set_updated_at ON {table_name}"
        )
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_updated_at_triggers()
    op.drop_index('ix_ai_generation_logs_customer_message_id', table_name='ai_generation_logs')
    op.drop_index('ix_ai_generation_logs_conversation_created', table_name='ai_generation_logs')
    op.drop_index('ix_ai_generation_logs_brand_id', table_name='ai_generation_logs')
    op.drop_table('ai_generation_logs')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_index('ix_messages_brand_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_order_id', table_name='conversations')
    op.drop_index('ix_conversations_customer_id', table_name='conversations')
    op.drop_index('ix_conversations_brand_status', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_orders_customer_id', table_name='orders')
    op.drop_table('orders')
    op.drop_table('knowledge_base_entries')
    op.drop_table('customers')
    op.drop_table('brands')
    # ### end Alembic commands ###
